# 0.2_ss_2.3_DP
- 動的計画法の写経

In [1]:
import numpy as np
import pandas as pd
import itertools
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()

## Napzack

### 全探索

In [2]:
# クラスの変数かな
n = 4
w = [2,1,3,2]
v = [3,2,4,2]
W = 5

In [3]:
def rec(i, j):
    ''' i 番目以降の品物から、重さがj以下となるように選ぶ
    '''
    # もう品物がない
    if i == n:
        return 0
    
    # 品物が入らない
    if j < w[i]:
        return rec(i+1, j)
    
    # 入る場合と入らない場合を返す
    return max(rec(i+1, j), rec(i+1, j-w[i]) + v[i])

In [4]:
rec(0, W)

7

### DP(Memo)

In [5]:
dp = -np.ones((n+1, W+1))

In [6]:
dp

array([[-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.]])

In [16]:
def rec(i, j):
    
    # 値が保存されている場合
    if dp[i][j] >= 0:
        logger.debug(f"Use saved for i: {i}, j: {j}")
        return dp[i][j]
    
    # ない
    if i == n:
        dp[i][j] = 0
        return dp[i][j]

    # 入らない
    if j < w[i]:
        dp[i][j] = rec(i+1, j)
        return dp[i][j]

    dp[i][j] = max(rec(i+1, j), rec(i+1, j-w[i])+v[i]) 
    return dp[i][j]

In [17]:
rec(0, W)

DEBUG:root:Use saved for i: 2, j: 5
DEBUG:root:Use saved for i: 3, j: 4
DEBUG:root:Use saved for i: 4, j: 1
DEBUG:root:Use saved for i: 4, j: 3
DEBUG:root:Use saved for i: 4, j: 1
DEBUG:root:Use saved for i: 4, j: 0
DEBUG:root:Use saved for i: 3, j: 2


7.0

In [18]:
dp

array([[-1., -1., -1., -1., -1.,  7.],
       [-1., -1., -1.,  4., -1.,  6.],
       [-1., -1.,  2.,  4.,  4.,  6.],
       [ 0.,  0.,  2.,  2.,  2.,  2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

### DP as a table
- 以下を解いているだけ

```
dp[n][j] = 0
dp[i][j] = 
    if j < w[j]: 
        dp[i+1][j]
    else:
        max(dp(i+1, j), dp[i+1, j-w[i]] + v[j])
```

In [38]:
dp = np.zeros((n+1, W+1))

for i in range(n-1, -1, -1):
    for j in range(W+1):
        if j < w[i]:
            dp[i][j] = dp[i+1][j]
        else:
            dp[i][j] = max(dp[i+1][j], dp[i+1][j-w[i]]+v[i])
            
print(dp[0][W])

7.0


### Dp loop forward

In [39]:
dp = np.zeros((n+1, W+1))
for i in range(n):
    for j in range(W+1):
        if j < w[i]:
            dp[i+1][j] = dp[i][j]
        else:
            dp[i+1][j] = max(dp[i][j], dp[i][j - w[i]] + v[i])

In [40]:
dp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 3., 3., 3.],
       [0., 2., 3., 5., 5., 5.],
       [0., 2., 3., 5., 6., 7.],
       [0., 2., 3., 5., 6., 7.]])

In [44]:
dp = np.zeros((n+1, W+1))
for i in range(n):
    for j in range(W+1):
        dp[i+1][j] = max(dp[i+1][j], dp[i][j])
        if j + w[i] <= W:
            dp[i+1][j+w[i]] = max(dp[i+1][j+w[i]], dp[i][j] + v[i])
            
print(dp[n][W])

7.0


In [45]:
dp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 3., 3., 3.],
       [0., 2., 3., 5., 5., 5.],
       [0., 2., 3., 5., 6., 7.],
       [0., 2., 3., 5., 6., 7.]])