# 0.4_ss_chap-2-3-napzack

## 最大共通文字列

### Greedy

In [1]:
from nltk.corpus import words
import random
import itertools
import logging
import numpy as np
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()
random.seed(0)

### One loop

In [4]:
n = 3
w = [3, 4, 2]
v = [4, 5, 3]
W = 7
dp = np.zeros((n+1, W+1))

In [6]:
for i in range(n):
    for j in range(W+1):
        if j < w[i]:
            dp[i+1][j] = dp[i][j]
        else:
            dp[i+1][j] = max(dp[i][j], dp[i+1][j-w[i]]+v[i])

In [7]:
dp

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  4.,  4.,  8.,  8.],
       [ 0.,  0.,  0.,  4.,  5.,  5.,  8.,  9.],
       [ 0.,  0.,  3.,  4.,  6.,  7.,  9., 10.]])

### 01

In [17]:
n = 3
w = [3, 4, 2]
v = [4, 5, 3]
W = 7
dp = np.zeros((W+1))

In [18]:
for i in range(n):
    for j in range(W, w[i]-1, -1):
        dp[j] = max(dp[j], dp[j-w[i]]+v[i])
        print(dp)

[0. 0. 0. 0. 0. 0. 0. 4.]
[0. 0. 0. 0. 0. 0. 4. 4.]
[0. 0. 0. 0. 0. 4. 4. 4.]
[0. 0. 0. 0. 4. 4. 4. 4.]
[0. 0. 0. 4. 4. 4. 4. 4.]
[0. 0. 0. 4. 4. 4. 4. 9.]
[0. 0. 0. 4. 4. 4. 5. 9.]
[0. 0. 0. 4. 4. 5. 5. 9.]
[0. 0. 0. 4. 5. 5. 5. 9.]
[0. 0. 0. 4. 5. 5. 5. 9.]
[0. 0. 0. 4. 5. 5. 8. 9.]
[0. 0. 0. 4. 5. 7. 8. 9.]
[0. 0. 0. 4. 5. 7. 8. 9.]
[0. 0. 0. 4. 5. 7. 8. 9.]
[0. 0. 3. 4. 5. 7. 8. 9.]


In [12]:
dp

array([0., 0., 3., 4., 5., 7., 8., 9.])

In [13]:
n = 3
w = [3, 4, 2]
v = [4, 5, 3]
W = 7
dp = np.zeros((W+1))

In [14]:
for i in range(n):
    for j in range(w[i], W+1):
        dp[j] = max(dp[j], dp[j-w[i]]+v[i])

In [15]:
dp

array([ 0.,  0.,  3.,  4.,  6.,  7.,  9., 10.])

In [23]:
n = 3
w = [3, 4, 2]
v = [4, 5, 3]
W = 7
dp = np.zeros((2, W+1))

In [24]:
for i in range(0, n):
    for j in range(0, W+1):
        if j < w[i]:
            dp[(i+1) & 1][j] = dp[i&1][j]
        else:
            dp[(i+1)&1][j] = max(dp[i&1][j], dp[(i+1)&1][j-w[i]]+v[i])

In [25]:
dp

array([[ 0.,  0.,  0.,  4.,  5.,  5.,  8.,  9.],
       [ 0.,  0.,  3.,  4.,  6.,  7.,  9., 10.]])

# Napzack 02

In [28]:
n = 4
w = np.array([2,1,3,2])
v = np.array([3,2,4,2])
W = 5

In [27]:
np.inf

inf

In [31]:
dp = np.ones((n+1, n*max(v)+1))*np.inf

In [33]:
dp[0][0] = 0
for i in range(n):
    for j in range(n*max(v)+1):
        if j < v[i]:
            dp[i+1][j] = dp[i][j]
        else:
            dp[i+1][j] = min(dp[i][j], dp[i][j-v[i]] + w[i])

In [34]:
dp

array([[ 0., inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
        inf, inf, inf, inf],
       [ 0., inf, inf,  2., inf, inf, inf, inf, inf, inf, inf, inf, inf,
        inf, inf, inf, inf],
       [ 0., inf,  1.,  2., inf,  3., inf, inf, inf, inf, inf, inf, inf,
        inf, inf, inf, inf],
       [ 0., inf,  1.,  2.,  3.,  3.,  4.,  5., inf,  6., inf, inf, inf,
        inf, inf, inf, inf],
       [ 0., inf,  1.,  2.,  3.,  3.,  4.,  5.,  6.,  6., inf,  8., inf,
        inf, inf, inf, inf]])

## 総和

In [42]:
n = 3
a = [3, 5, 8]
m = [3, 2, 2]
K = 17

In [44]:
dp = np.zeros((n+1, K+1), dtype=bool)
dp[0][0] = True 

for i in range(n):
    for j in range(K+1):
        k = 0
        while((k <= m[i]) & (k * a[i] <= j)):
            dp[i+1][j] |= dp[i][j - k*a[i]]
            k += 1

In [45]:
dp

array([[ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [ True, False, False,  True, False, False,  True, False, False,
         True, False, False, False, False, False, False, False, False],
       [ True, False, False,  True, False,  True,  True, False,  True,
         True,  True,  True, False,  True,  True, False,  True, False],
       [ True, False, False,  True, False,  True,  True, False,  True,
         True,  True,  True, False,  True,  True, False,  True,  True]])

In [53]:
dp = np.ones(K+1)*-1
dp[0] = 0

for i in range(n):
    for j in range(K+1):
        if dp[j] >= 0:
            dp[j] = m[i]
        elif (j < a[i]) | (dp[j-a[i]]<= 0):
            dp[j] = -1
        else:
            dp[j] = dp[j-a[i]] - 1

In [55]:
dp[K]

1.0

In [56]:
dp

array([ 2., -1., -1.,  2., -1.,  2.,  2., -1.,  2.,  2.,  2.,  2., -1.,
        2.,  2., -1.,  2.,  1.])

## 最長増加部分列
- dp[i] 最後が a[i] である最長の部分列の長さ

In [58]:
n = 5
a = [4,2,3,1,5]

In [60]:
dp = np.zeros(n+1)
for i in range(n):
    dp[i] = 1
    for j in range(i):
        if not a[j] < a[i]:
            continue
        dp[i] = max(dp[i], dp[j]+1)

print(max(0, dp[i])) 

3.0


In [65]:
dp = np.ones(n+1)*np.inf
for i in range(n):
    index = np.searchsorted(dp, a[i])
    dp[index] = a[i]

In [66]:
dp

array([ 1.,  3.,  5., inf, inf, inf])

0

### 分割

In [79]:
n = 4
m = 3
M = 10000
dp = np.zeros((m+1, n+1))

dp[0][0]=1
for i in range(1, m+1):
    for j in range(n+1):
        if (j-i >=0):
            dp[i][j] = (dp[i-1][j] + dp[i][j-i]) % M
        else:
            dp[i][j] = dp[i-1][j]

In [80]:
dp

array([[1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 2., 2., 3.],
       [1., 1., 2., 3., 4.]])

In [72]:
dp[m][n]

4.0

In [74]:
dp[2][4]

3.0

### 重複組合せ

In [81]:
n = 3
m = 3
a = [1,2,3]
M = 10000

In [82]:
dp = np.zeros((n+1, m+1))

In [84]:
# 1つも選ばない
for i in range(n+1):
    dp[i][0] = 1 

for i in range(n):
    for j in range(m+1):
        if j - 1 - a[i] >= 0:
            dp[i+1][j] = (dp[i+1][j-1] + dp[i][j] - dp[i][j-1-a[i]] + M) % M
        else:
            dp[i+1][j] = (dp[i+1][j-1] + dp[i][j]) % M

In [85]:
dp

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 2., 1.],
       [1., 3., 5., 6.]])

# Heap

In [93]:
n = 10
size = 0
heap = np.zeros(n)

def push(x: int):
    size += 1
    i = size
    
    while i > 0:
        # parent
        p = int((i-1)/2)
        
        # break
        if heap[p] <= x:
            break

        # 親をおろして自分が上に
        heap[i] = heap[p]
        i = p
    
    heap[i] = x

def pop() -> int:
    # 返り値
    ret = heap[0]
    # 根にもってくる
    size -= 1
    x = heap[size]
    
    # 根から下ろす
    i = 0
    while(i*2 + 1 < size):
        # 子を比較
        a = i*2 + 1
        b = i*2 + 2
        if(b < size & heap[b] < heap[a]):
            a = b
            
        # 逆転していないなら終わり
        if heap[a] >= x:
            break
        
        # 子を持ち上げる
        heap[i] = heap[a]
        i = a
    
    heap[i] = x
    
    return ret
        

# ガソリン

In [112]:
import heapq



def solve():
    N = 4
    L = 25
    P = 10
    A = [10, 14, 20, 21]
    B = [10,  5,  2,  4]
    
    # ゴールをガソリンスタンドに追加
    A.append(L)
    B.append(0)
    N += 1

    # ガソリンスタンド
    que = []
    heapq.heapify(que)
    ans = 0
    pos = 0
    tank = P

    for i in range(N):
        # 進む距離
        d = A[i] - pos

        # ガソリンを補給
        while tank-d < 0:
            if len(que) == 0:
                return -1
            
            # reverse the heap
            tank -= heapq.heappop(que)
            ans += 1
        
        tank -= d
        pos = A[i]
        heapq.heappush(que, -B[i])
    
    return ans

In [113]:
solve()

2

# Fence repair

In [123]:
N = 3
L = [8, 5, 8]

ans = 0
ll = 0

que = []
heapq.heapify(que)
for i in range(N):
    heapq.heappush(que, L[i])

while(len(que) > 1):
    l1 = heapq.heappop(que)
    l2 = heapq.heappop(que)
    
    ans += l1 + l2
    heapq.heappush(que, l1+l2)

In [124]:
que

[21]

# Union find tree

In [236]:
class UnionFindTree():
    def __init__(self, n:int):
        self.n = n
        self.par = np.array(range(n))
        self.rank = np.zeros((n,), dtype = np.int8)
    
    def find(self, x: int):
        if self.par[x] == x:
            return x
        else:
            self.par[x] = self.find(self.par[x])
            return self.par[x]
    
    def unite(self, x: int, y:int):
        x = self.find(x)
        y = self.find(y)
        if x == y:
            return
        
        if self.rank[x] < self.rank[y]:
            self.par[x] = y
        else:
            self.par[y] = x
            if self.rank[x] == self.rank[y]:
                self.rank[x] += 1
    
    def same(self, x: int, y: int) -> bool:
        return self.find(x) == self.find(y)

In [237]:
N = 100
K = 7
T = [1,  2,2,2,1,2,1,]
X = [101,1,2,3,1,3,5,] 
Y = [1,  2,3,3,3,1,5,]

tree = UnionFindTree(N*3)
ans = 0
for i in range(K):
    t = T[i]
    x = X[i] - 1
    y = Y[i] - 1
    
    def correct_input():
        if x < 0:
            return False
        if N <= x:
            return False
        if y < 0:
            return False
        if N <= y:
            return False
        return True
    
    def logic():
        # 正しくない番号
        if not correct_input():
            logger.debug(f"Out of bounds, x:{x}, y:{y}, N:{N}")
            return 1

        if t == 1:
            # x と y は同じ種類
            if tree.same(x, y + N):
                logger.debug("Eats")
                return 1
    
            if tree.same(x, y + 2*N):
                logger.debug("Eats")
                return 1

            tree.unite(x,y)
            tree.unite(x+N, y+N)
            tree.unite(x+N*2, y+N*2)
            return 0

        if t == 2:
            # x は y を食べる
            if tree.same(x, y):
                logger.debug("Same type")
                return 1
            
            if tree.same(x, y+2*N):
                logger.debug("Same type")
                return 1

            tree.unite(x, y + N)
            tree.unite(x + N, y + 2*N)
            tree.unite(x + 2*N, y)
            return 0
    
    logger.debug(f"Check i: {i}")
    ans += logic()
            
        

DEBUG:root:Check i: 0
DEBUG:root:Out of bounds, x:100, y:0, N:100
DEBUG:root:Check i: 1
DEBUG:root:Check i: 2
DEBUG:root:Check i: 3
DEBUG:root:Same type
DEBUG:root:Check i: 4
DEBUG:root:Eats
DEBUG:root:Check i: 5
DEBUG:root:Check i: 6


In [238]:
ans

3